# TODO: explain it
name: wagon-cliche

# TODO: explain it
# subdomain: sample

# TODO: explain it
# domains: [www.example.com, example.com]

# TODO: explain it
locales: [en]

seo_title: I'm a Cliché
meta_keywords: "I'm a cliche label"
meta_description: ""